### ISSUE TITLE
Black screen when using script. Main menu usable when adding a few lines in custom-es-config

### ISSUE THREAD

**Issue by Delthax11** [ZFEbHVUE/Build-CRT-15KHz-Batocera#142]
Hello.

When I use the script, I got a black screen. The tv tries to show something but can't.
The pc is a Lenovo Thinkcentre M910q
CPU: Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
GPU: Intel Corporation"HD Graphics 530
Cpu number: 4
Cpu max frequency: 3100 MHz
Cpu feature: avx2
OS version: 35 2022/09/17 13:13
TV: LG 21FS7AL
I connect the computer to the tv with a VGA to YPbPr transcoder.
The VGA port it's actually a Displayport.
When using the script I tried with generic_15 and ntsc, same result. 

If I add these lines to custom-es-config, i can get the menu to work but if I try to launch a game I got a black screen and can't get back to the main menu.

xrandr -display :0.0 --newmode "2560x240_60" 52.12 2560 2664 2912 3328 240 242 245 261 -hsync -vsync
xrandr -display :0.0 --addmode DP-3 "2560x240_60"
xrandr -display :0.0 --output DP-3 --mode "2560x240"

It's a bit shaky tho.

Thanks.

This what it shows when I use the script.

      ____    __   ____  _____  ___  ____  ____    __
     (  _ \  /__\ (_  _)(  _  )/ __)( ___)(  _ \  /__\
      ) _ < /(__)\  )(   )(_)(( (__  )__)  )   / /(__)\
     (____/(__)(__)(__) (_____)\___)(____)(_)\_)(__)(__)
                 R E A D Y   T O   R E T R O

-- type 'batocera-check-updates' to check for stable branch --
-- add 'beta' switch to check for latest arch developments  --

Disk format: ext4
Temperature: 32°C
Architecture: x86_64
System: Linux 5.18.19
Available memory: 15308/15890 MB
Cpu model: Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
Cpu number: 4
Cpu max frequency: 3100 MHz
Cpu feature: avx2
OS version: 35 2022/09/17 13:13

[root@BATOCERA /userdata/system]# cd /userdata/system/BUILD_15KHz/Batocera_ALLINONE
[root@BATOCERA /userdata/system/BUILD_15KHz/Batocera_ALLINONE]# chmod 755 BUILD_15KHZ_BATOCERA.sh
[root@BATOCERA /userdata/system/BUILD_15KHz/Batocera_ALLINONE]# ./BUILD_15KHZ_BATOCERA.sh
#######################################################################
#######################################################################

                       PRESS ENTER TO START
Version 35
#######################################################################
#######################################################################

        1 : Intel Corporation"HD Graphics 530

#######################################################################
#######################################################################
        Selected card = Intel Corporation"HD Graphics 530
#######################################################################
#######################################################################

                        1 : DP-1
                        2 : DP-2
                        3 : DP-3
                        4 : HDMI-A-1
                        5 : HDMI-A-2
                        6 : HDMI-A-3

#######################################################################
#######################################################################
                                  3
                    your choice is :  DP-3
                       PRESS ENTER TO CONTINUE

#######################################################################
#######################################################################

                        1 : 15KHz
                        2 : 25KHz
                        3 : 31KHz

#######################################################################
#######################################################################
                                  1
                    your choice is :  15KHz

#######################################################################
#######################################################################

                        1 : arcade_15
                        2 : arcade_15_25_31
                        3 : arcade_15ex
                        4 : generic_15
                        5 : ntsc
                        6 : pal

#######################################################################
#######################################################################
                                  5
                    your choice is :  ntsc
                       PRESS ENTER TO CONTINUE

#######################################################################
#######################################################################

                        1 : YES
                        2 : NO

#######################################################################
#######################################################################
                                  1
                    your choice is :  YES

#######################################################################
#######################################################################

                        1 : arcade_15
                        2 : arcade_15_SR480
                        3 : arcade_15_SR240
                        4 : arcade_15_25_31
                        5 : arcade_15ex
                        6 : generic_15
                        7 : generic_15_SR480
                        8 : generic_15_SR240
                        9 : ntsc
                        10 : pal

#######################################################################
#######################################################################
                                  9
                    your choice is :  ntsc
                       PRESS ENTER TO CONTINUE

#######################################################################
#######################################################################

                        1 : 720x480ieS
                        2 : 640x480ieS

#######################################################################
#######################################################################
                                  2
                    your choice is :  640x480ieS

#######################################################################
#######################################################################

                        1 : 720x480_60iHz
                        2 : 640x480_60iHz

#######################################################################
#######################################################################
                                  2
                    Your choice is :  640x480_60iHz
                       PRESS ENTER TO CONTINUE

#######################################################################
#######################################################################

                        1 : None
                        2 : Clockwise
                        3 : Counter-Clockwise

#######################################################################
#######################################################################
                                  1
                    Your choice is :  None

#######################################################################
#######################################################################

                        1 : NORMAL
                        2 : TATE90
                        3 : INVERTED
                        4 : TATE270

#######################################################################
#######################################################################
                                  1
                    Your choice is :  NORMAL
                       PRESS ENTER TO CONTINUE
#######################################################################
#######################################################################

                        1 : YES
                        2 : NO

#######################################################################
#######################################################################
                                  2
                    your choice is : Don't mess with it, sorry ;).

#######################################################################
#######################################################################

                        1 : Activate(reduce input lag)
                        2 : Keep default

#######################################################################
#######################################################################

                    your choice is : Batocera default usb polling rate
mount -o remount, rw /boot

#######################################################################
#######################################################################
                        1 : usb-HORI_CO._LTD._Fighting_Commander-event-joystick
                        2 : usb-HORI_CO._LTD._Fighting_Commander-joystick
                        0 : Exit for USB Arcade Encoder(s)
#######################################################################
#######################################################################

#######################################################################
#######################################################################

                       PRESS ENTER TO FINISH
Making /boot writable...
Mounting the overlay file...
Saving the real overlay to disk...
sending incremental file list
./
nohup.out
.cache/
.cache/openbox/
.cache/openbox/openbox.log
.cache/openbox/sessions/
.config/
.config/pulse/
.config/pulse/cookie
.dbus/
.dbus/session-bus/
.dbus/session-bus/89ee2a85cbfd5afa07a4771663731631-0
.local/
.local/state/
.local/state/pipewire/
.local/state/pipewire/media-session.d/
.local/state/pipewire/media-session.d/default-routes
.local/state/pipewire/media-session.d/restore-stream
etc/
etc/hosts
etc/switchres.ini
etc/switchres.ini.bak
etc/X11/xorg.conf.d/
etc/X11/xorg.conf.d/10-monitor.conf
etc/X11/xorg.conf.d/20-amdgpu.conf
etc/X11/xorg.conf.d/20-radeon.conf
etc/init.d/
etc/init.d/S05nvidia
etc/udev/rules.d/
etc/udev/rules.d/98-keyboards-exotics.rules
etc/udev/rules.d/99-jammasd.rules
etc/udev/rules.d/99-joysticks-exotics.rules
lib/firmware/edid/
lib/firmware/edid/arcade_15.bin
lib/firmware/edid/arcade_15_25.bin
lib/firmware/edid/arcade_15_25_31.bin
lib/firmware/edid/arcade_15_31.bin
lib/firmware/edid/arcade_15_SR240.bin
lib/firmware/edid/arcade_15_SR480.bin
lib/firmware/edid/arcade_15_SR600.bin
lib/firmware/edid/arcade_15ex.bin
lib/firmware/edid/arcade_25.bin
lib/firmware/edid/arcade_31.bin
lib/firmware/edid/d9200.bin
lib/firmware/edid/d9400.bin
lib/firmware/edid/d9800.bin
lib/firmware/edid/generic_15.bin
lib/firmware/edid/generic_15_SR240.bin
lib/firmware/edid/generic_15_SR480.bin
lib/firmware/edid/generic_15_SR600.bin
lib/firmware/edid/h9110.bin
lib/firmware/edid/k7000.bin
lib/firmware/edid/k7131.bin
lib/firmware/edid/m2929.bin
lib/firmware/edid/m3129.bin
lib/firmware/edid/ms2930.bin
lib/firmware/edid/ms929.bin
lib/firmware/edid/ntsc.bin
lib/firmware/edid/pal.bin
lib/firmware/edid/pc_31_120.bin
lib/firmware/edid/pc_70_120.bin
lib/firmware/edid/polo.bin
lib/firmware/edid/pstar.bin
lib/firmware/edid/r666b.bin
lib/firmware/edid/vesa_1024.bin
lib/firmware/edid/vesa_480.bin
lib/firmware/edid/vesa_600.bin
lib/firmware/edid/vesa_768.bin
usr/bin/
usr/bin/batocera-nvidia
usr/bin/batocera-resolution
usr/bin/emulationstation-standalone
usr/bin/jammASDSplit
usr/bin/retroarch
usr/share/X11/xkb/compiled/
usr/share/batocera/splash/
usr/share/batocera/splash/boot-logo.png
usr/share/emulationstation/themes/es-theme-carbon/art/consoles/
usr/share/emulationstation/themes/es-theme-carbon/art/consoles/CRT.png
usr/share/emulationstation/themes/es-theme-carbon/art/logos/
usr/share/emulationstation/themes/es-theme-carbon/art/logos/CRT.svg
usr/share/evmapy/
usr/share/evmapy/CRT.sh.keys
usr/share/fonts/X11/100dpi/
usr/share/fonts/X11/75dpi/
usr/share/fonts/X11/cyrillic/
usr/share/fonts/X11/encodings/large/

sent 16,036,872 bytes  received 1,320 bytes  32,076,384.00 bytes/sec
total size is 30,426,269  speedup is 1.90
Umounting the overlay file...
Making /boot read only...
Synchronizing...
Success.
[root@BATOCERA /userdata/system/BUILD_15KHz/Batocera_ALLINONE]#

**Comment by Delthax11** [comment]
The menu looks much better with these lines

xrandr -display :0.0 --newmode "2560x480_60" 52.22 2560 2664 2912 3328 480 483 489 523 interlace -hsync -vsync
xrandr -display :0.0 --addmode DP-3 "2560x480_60"
xrandr -display :0.0 --output DP-3 --mode "2560x480"

Still no image when I try to launch a game

**Comment by Delthax11** [comment]
There has been some progress.

The NES games are working now.

I set the super resolution to 2560 in the script, and changed the Dot Clock manually to 10. Sadly when I quit to the main menu I got a black screen.

I checked the "first_script.sh" file and it says

gameStop)

		xrandr -display :0.0 -o normal
		xrandr -display :0.0 --output DP-3 --set TearFree OFF
		xrandr -display :0.0 --output DP-3 --mode "640x480"

I changed it to "2560x480" but there was no luck.

The others consoles didn't work, I changed the dot clock to 25 to see if there was luck there but no (NES still worked).

Any ideas??

**Comment by ZFEbHVUE** [comment]
Hi Delthax11 : come on discord : Batocera.linux   channel #CRT 
Have fun.

Ask @rion and me

Stéphane (ZFEbHVUE).
