### ISSUE TITLE
gamecube issue

### ISSUE THREAD

**Issue by popoma67** [ZFEbHVUE/Build-CRT-15KHz-Batocera#156]
I have a caicos-based GPU and in the gamecube retroarch emulator the image is displayed out of sync and in the gamecube dolphin emulator the vsync when activated gives a flickering image

**Comment by Redemp** [comment]
> I have a caicos-based GPU and in the gamecube retroarch emulator the image is displayed out of sync and in the gamecube dolphin emulator the vsync when activated gives a flickering image

Please join the official Batocera Discord channel and head over to the # CRT channel so we can troubleshoot there.
